# Generated by Django 2.2.3 on 2019-07-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(db_index=True, max_length=20)),
                ('team2', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(default='new', unique=True)),
                ('t1_c', models.IntegerField(db_index=True, default='0', max_length=2)),
                ('t2_c', models.IntegerField(db_index=True, default='0', max_length=2)),
                ('c1', models.CharField(db_index=True, max_length=5)),
                ('c2', models.CharField(db_index=True, max_length=5)),
                ('c3', models.CharField(db_index=True, max_length=5)),
                ('c4', models.CharField(blank=True, db_index=True, max_length=5)),
                ('c5', models.CharField(blank=True, db_index=True, max_length=5)),
                ('date', models.CharField(db_index=True, default='0.0.0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('matches', models.ManyToManyField(related_name='competitions', to='portal.Match')),
            ],
        ),
    ]
